version: 2.1

jobs:
  build:
    docker:
      - image: circleci/rust:1.31.1
    steps:
      - run:
          name: "where am i (before checkout)"
          command: |
            pwd
            ls -al
      - checkout
      - run:
          name: "where am i (after checkout)"
          command: |
            pwd
            ls -al
      - run:
          command: |
            cargo test
          name: "tests"
