version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run:
        command: |
          echo "Greetings, Earthlings!"
          notacommand
        name: "mars"
